-- MySQL Script generated by MySQL Workbench
-- Thu Feb 13 12:24:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `idmarca` INT NOT NULL DEFAULT Guess,
  `graduacio` VARCHAR(45) NULL DEFAULT '0,1',
  `color m` VARCHAR(45) NULL DEFAULT 'rojo',
  `color v` VARCHAR(45) NULL DEFAULT 'azul',
  `montura` VARCHAR(45) NULL DEFAULT 'pasta',
  `preu` DECIMAL(100) NULL DEFAULT 110,
  PRIMARY KEY (`idmarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `idClients` INT NOT NULL DEFAULT 1,
  `nom` VARCHAR(45) NULL DEFAULT 'Juan',
  `adreça` VARCHAR(45) NULL DEFAULT 'Calle Pino',
  `telefon` DECIMAL(9) NULL DEFAULT 567589049,
  `email` VARCHAR(45) NULL DEFAULT 'juanelpino@hotmail.com',
  `data registre` DECIMAL(8) NULL DEFAULT 12/12/1994,
  `recomanat` VARCHAR(45) NULL DEFAULT '2',
  PRIMARY KEY (`idClients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ulleres` (
  `idulleres` INT NOT NULL,
  `color m` VARCHAR(45) NULL,
  `montura` VARCHAR(45) NULL,
  `graduacio` DECIMAL(10) NULL,
  `color v` VARCHAR(45) NULL,
  `preu` DECIMAL(100) NULL,
  `Clients_idClients` INT NOT NULL,
  PRIMARY KEY (`idulleres`),
  INDEX `fk_ulleres_Clients1_idx` (`Clients_idClients` ASC) VISIBLE,
  CONSTRAINT `fk_ulleres_Clients1`
    FOREIGN KEY (`Clients_idClients`)
    REFERENCES `mydb`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveidor` (
  `idproveidor` INT NOT NULL DEFAULT 3,
  `nom` VARCHAR(45) NULL DEFAULT 'Paco',
  `adreça` VARCHAR(45) NULL DEFAULT 'calle milan',
  `fax` VARCHAR(45) NULL DEFAULT '748490312',
  `nif` VARCHAR(45) NULL DEFAULT '45460019T',
  `marca_idmarca` INT NOT NULL,
  `ulleres_idulleres` INT NOT NULL,
  `ulleres_idmarca` INT NOT NULL,
  PRIMARY KEY (`idproveidor`),
  INDEX `fk_proveidor_marca_idx` (`marca_idmarca` ASC) VISIBLE,
  INDEX `fk_proveidor_ulleres1_idx` (`ulleres_idulleres` ASC, `ulleres_idmarca` ASC) VISIBLE,
  CONSTRAINT `fk_proveidor_marca`
    FOREIGN KEY (`marca_idmarca`)
    REFERENCES `mydb`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveidor_ulleres1`
    FOREIGN KEY (`ulleres_idulleres`)
    REFERENCES `mydb`.`ulleres` (`idulleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleat` (
  `idempleat` INT NOT NULL DEFAULT 1,
  `idventa` INT NOT NULL DEFAULT 12,
  `Clients_idClients` INT NOT NULL,
  PRIMARY KEY (`idempleat`, `idventa`),
  INDEX `fk_empleat_Clients1_idx` (`Clients_idClients` ASC) VISIBLE,
  CONSTRAINT `fk_empleat_Clients1`
    FOREIGN KEY (`Clients_idClients`)
    REFERENCES `mydb`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
$$

DELIMITER ;

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
